// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file is part of IntelliHR Backend API Documentation.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@intellihr.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/register": {
            "post": {
                "tags": ["Auth"],
                "summary": "Register Organization & Admin",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["company_name", "first_name", "last_name", "email", "password"],
                            "properties": {
                                "company_name": {"type": "string", "example": "Acme Corp"},
                                "domain": {"type": "string", "example": "acme.com"},
                                "first_name": {"type": "string", "example": "John"},
                                "last_name": {"type": "string", "example": "Doe"},
                                "email": {"type": "string", "example": "admin@acme.com"},
                                "password": {"type": "string", "example": "Secret123!"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Created"},
                    "400": {"description": "Bad Request"}
                }
            }
        },
        "/auth/login": {
            "post": {
                "tags": ["Auth"],
                "summary": "Authenticate User",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": {"type": "string", "example": "admin@acme.com"},
                                "password": {"type": "string", "example": "Secret123!"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "OK - Returns Tokens & User info"},
                    "401": {"description": "Unauthorized"}
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "tags": ["Auth"],
                "summary": "Refresh Access Token",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["refresh_token"],
                            "properties": {
                                "refresh_token": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/auth/me": {
            "get": {
                "tags": ["Auth"],
                "summary": "Get Profile of Current User",
                "security": [{"BearerAuth": []}],
                "responses": {
                    "200": {"description": "OK"}
                }
            }
        },
        "/employees": {
            "get": {
                "tags": ["Employees"],
                "summary": "List Employees",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"name": "search", "in": "query", "type": "string"},
                    {"name": "page", "in": "query", "type": "integer", "default": 1},
                    {"name": "limit", "in": "query", "type": "integer", "default": 20}
                ],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "tags": ["Employees"],
                "summary": "Create Employee",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["first_name", "last_name", "email", "joining_date"],
                            "properties": {
                                "first_name": {"type": "string"},
                                "last_name": {"type": "string"},
                                "email": {"type": "string"},
                                "joining_date": {"type": "string", "example": "2026-08-01"}
                            }
                        }
                    }
                ],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/departments": {
            "get": {
                "tags": ["Departments"],
                "summary": "List Departments",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "tags": ["Departments"],
                "summary": "Create Department",
                "security": [{"BearerAuth": []}],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/attendance/check-in": {
            "post": {
                "tags": ["Attendance"],
                "summary": "Check-In Attendance",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/leaves/apply/{emp_id}": {
            "post": {
                "tags": ["Leaves"],
                "summary": "Apply for Leave",
                "security": [{"BearerAuth": []}],
                "parameters": [
                    {"name": "emp_id", "in": "path", "required": true, "type": "string"}
                ],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/payroll-runs": {
            "get": {
                "tags": ["Payroll"],
                "summary": "List Payroll Runs",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            },
            "post": {
                "tags": ["Payroll"],
                "summary": "Create Payroll Run",
                "security": [{"BearerAuth": []}],
                "responses": {"201": {"description": "Created"}}
            }
        },
        "/workflows/templates": {
            "get": {
                "tags": ["Workflows"],
                "summary": "List Workflow Templates",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/notifications/me": {
            "get": {
                "tags": ["Notifications"],
                "summary": "List My In-App Notifications",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        },
        "/announcements": {
            "get": {
                "tags": ["Announcements"],
                "summary": "List Company Announcements",
                "security": [{"BearerAuth": []}],
                "responses": {"200": {"description": "OK"}}
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Enter your JWT token as: Bearer <token>"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "IntelliHR HRMS API Documentation",
	Description:      "Interactive Swagger UI Documentation for IntelliHR Multi-Tenant HRMS Backend API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
